version: "3"
services:
  app:
    container_name: snippetbox
    restart: unless-stopped
    build: .
    volumes:
      - .:/go/src/snippetbox
    ports:
        - "4000:4000"
    networks: 
        - fullstack 
    depends_on: 
        - db
    environment: 
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_SCHEMA: ${DB_SCHEMA}

  db:
    container_name: database
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_SCHEMA}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
        - "33065:3306"
    networks: 
        - fullstack 
    volumes:
        - database_data:/var/lib/mysql

volumes: 
    database_data:

networks: 
    fullstack:
        driver: bridge